<?php
/**
 * @file
 * Install, update, and uninstall hooks for the Data Layer module.
 */

/**
 * Implements hook_uninstall().
 */
function datalayer_uninstall() {
  // Remove all configurations.
  global $conf;
  foreach($conf as $key => $value) {
    if (0 === strpos($key, 'datalayer_')) {
      // @FIXME
// // @FIXME
// // The correct configuration object could not be determined. You'll need to
// // rewrite this call manually.
// variable_del($conf[$key]);

    }
  }
}
